<?php

/**
 * Helper function to install default credit types.
 */
function course_credit_test_create_types() {
  // Create credit types.

  $credit_type = array(
    'type' => 'nonvariable',
    'title' => 'Non-variable',
    'description' => 'A non-variable credit type.',
    'increments' => 0,
    'min' => 0,
    'max' => 5,
    'enable_variable_credit' => 0,
  );
  course_credit_save_credit_type($credit_type);

  $credit_type = array(
    'type' => 'variable',
    'title' => 'Variable',
    'description' => 'A variable credit type.',
    'increments' => 0.25,
    'min' => 1,
    'max' => 5,
    'enable_variable_credit' => 1,
  );
  course_credit_save_credit_type($credit_type);
}

function course_credit_test_create_profile2_field() {
  // Create fields for mapping tests.

  $field = array(
    'field_name' => 'user_type_profile2',
    'type' => 'list_text',
    'translatable' => TRUE,
    'settings' => array(
      'allowed_values' => array(
        'red' => 'Red',
        'blue' => 'Blue',
      ),
    ),
  );
  field_create_field($field);

  $instance = array(
    'entity_type' => 'profile2',
    'field_name' => 'user_type_profile2',
    'bundle' => 'main',
    'label' => 'User type 2',
    'widget_type' => 'options_select',
  );
  field_create_instance($instance);
}

function course_credit_test_create_user_field() {
  // Create fields for mapping tests.

  $field = array(
    'field_name' => 'user_type_profile1',
    'type' => 'list_text',
    'translatable' => TRUE,
    'settings' => array(
      'allowed_values' => array(
        'green' => 'Green',
        'yellow' => 'Yellow',
      ),
    ),
  );
  field_create_field($field);

  $instance = array(
    'entity_type' => 'user',
    'field_name' => 'user_type_profile1',
    'bundle' => 'user',
    'label' => 'User type 1',
    'widget_type' => 'options_select',
  );
  field_create_instance($instance);
}
